apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: loadbalancer-ips
spec:
  cidr: 192.168.86.200/29
  ipipMode: Never
  vxlanMode: Never
  nodeSelector: all()
---
apiVersion: projectcalico.org/v3
kind: BGPAdvertisement
metadata:
  name: loadbalancer-bgp-adv
spec:
  serviceLoadBalancerIPs:
    - 192.168.86.200/29
