persistentVolumeClaim:
  enabled: true
  storageClass: "longhorn"
  size: 5Gi

adminPassword: "admin-change-me"

serviceWeb:
  loadBalancerIP: 192.168.86.201
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.86.201
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDhcp:
  enabled: "false"

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - unbound.dns.svc.cluster.local
  - unbound.dns.svc.cluster.local
