global:
  storageClass:
    defaultClass: true

persistence:
  defaultClassReplicaCount: 1  # Configured for single-node K3s setup

defaultSettings:
  defaultDataPath: /var/lib/longhorn
  replicaAutoBalance: disabled
  storageMinimalAvailablePercentage: 15
  createDefaultDiskLabeledNodes: true

ingress:
  enabled: false

longhornUI:
  replicas: 1
