apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: dns
  labels:
    app: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
        - name: unbound
          image: mvance/unbound:1.19.0
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: dns
spec:
  selector:
    app: unbound
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53