server:
  persistentVolume:
    enabled: true
    storageClass: "longhorn"
    size: 10Gi
  retention: 15d
  retentionSize: 7GB
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.homelab.local

alertmanager:
  enabled: false

nodeExporter:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 24Mi
    limits:
      cpu: 50m
      memory: 64Mi

kube-state-metrics:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
