server:
  persistentVolume:
    enabled: true
    storageClass: "longhorn"
    size: 10Gi
  retention: 15d
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.homelab.local

alertmanager:
  enabled: false

nodeExporter:
  enabled: true

kube-state-metrics:
  enabled: true
