apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://docs.tigera.io/calico/charts'
    chart: tigera-operator
    targetRevision: v3.28.0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tigera-operator
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
