apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unbound-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jeysibn/homelab-gitops.git'
    targetRevision: HEAD
    path: kubernetes/apps/dns
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://mojo2600.github.io/pihole-kubernetes/'
      chart: pihole
      targetRevision: 2.27.0
      helm:
        valueFiles:
          - $values/kubernetes/apps/dns/pihole-values.yaml
    - repoURL: 'https://github.com/jeysibn/homelab-gitops.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true