name: "Terraform Proxmox Provision"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Connect to local homelab network via Tailscale (Remove if using a Self-Hosted Runner)
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      # Configure SSH key for bpg/proxmox provider disk upload
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROXMOX_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 192.168.86.61 >> ~/.ssh/known_hosts

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: 
          
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format & Validate
        run: |
          terraform fmt -check
          terraform validate

      - name: Run TFLint
        run: |
          tflint --init
          tflint

      - name: Terraform Plan
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_API_URL }}
          TF_VAR_proxmox_api_token: ${{ secrets.PROXMOX_API_TOKEN }}
          TF_VAR_proxmox_node: ${{ secrets.PROXMOX_NODE }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_API_URL }}
          TF_VAR_proxmox_api_token: ${{ secrets.PROXMOX_API_TOKEN }}
          TF_VAR_proxmox_node: ${{ secrets.PROXMOX_NODE }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform apply -auto-approve -input=false